services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.5.0
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_CLIENT_TIME: 2000
        ports:
          - "2181:2181"
        networks:
          - kafka-network

    kafka:
      image: confluentinc/cp-kafka:7.5.0
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      networks:
      - kafka-network
    mongodb:
      image: mongo:4.4
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data:/data/db
      networks:
        - kafka-network

    app:
      build: .
      container_name: app
      volumes: 
        - .:/usr/src/app
        - /usr/src/app/node_modules
      command: yarn dev
      ports:
        - "3105:3000"
      depends_on:
        - kafka
        - mongodb
      networks:
      - kafka-network

volumes:
    mongodb_data:

networks:
  kafka-network:
    driver: bridge